Config.Weapons = {
    WEAPON_KNIFE = { item = 'knife', label = ('weapon_knife') },
    WEAPON_NIGHTSTICK = { item = 'nightstick', label = ('weapon_nightstick') },
    WEAPON_HAMMER = { item = 'hammer', label = ('weapon_hammer') },
    WEAPON_BAT = { item = 'bat', label = ('weapon_bat') },
    WEAPON_GOLFCLUB = { item = 'golfclub', label = ('weapon_golfclub') },
    WEAPON_CROWBAR = { item = 'crowbar', label = ('weapon_crowbar') },
    WEAPON_PISTOL = { item = 'pistol', label = ('weapon_pistol') },
    WEAPON_COMBATPISTOL = { item = 'combatpistol', label = ('weapon_combatpistol') },
    WEAPON_APPISTOL = { item = 'appistol', label = ('weapon_appistol') },
    WEAPON_PISTOL50 = { item = 'pistol50', label = ('weapon_pistol50') },
    WEAPON_MICROSMG = { item = 'microsmg', label = ('weapon_microsmg') },
    WEAPON_SMG = { item = 'smg', label = ('weapon_smg') },
    WEAPON_ASSAULTSMG = { item = 'assaultsmg', label = ('weapon_assaultsmg') },
    WEAPON_ASSAULTRIFLE = { item = 'assaultrifle', label = ('weapon_assaultrifle') },
    WEAPON_CARBINERIFLE = { item = 'carbinerifle', label = ('weapon_carbinerifle') },
    WEAPON_ADVANCEDRIFLE = { item = 'advancedrifle', label = ('weapon_advancedrifle') },
    WEAPON_MG = { item = 'mg', label = ('weapon_mg') },
    WEAPON_COMBATMG = { item = 'combatmg', label = ('weapon_combatmg') },
    WEAPON_PUMPSHOTGUN = { item = 'pumpshotgun', label = ('weapon_pumpshotgun') },
    WEAPON_SAWNOFFSHOTGUN = { item = 'sawnoffshotgun', label = ('weapon_sawnoffshotgun') },
    WEAPON_ASSAULTSHOTGUN = { item = 'assaultshotgun', label = ('weapon_assaultshotgun') },
    WEAPON_BULLPUPSHOTGUN = { item = 'bullpupshotgun', label = ('weapon_bullpupshotgun') },
    WEAPON_STUNGUN = { item = 'stungun', label = ('weapon_stungun') },
    WEAPON_SNIPERRIFLE = { item = 'sniperrifle', label = ('weapon_sniperrifle') },
    WEAPON_HEAVYSNIPER = { item = 'heavysniper', label = ('weapon_heavysniper') },
    WEAPON_REMOTESNIPER = { item = 'remotesniper', label = ('weapon_remotesniper') },
    WEAPON_GRENADELAUNCHER = { item = 'grenadelauncher', label = ('weapon_grenadelauncher') },
    WEAPON_RPG = { item = 'rpg', label = ('weapon_rpg') },
    WEAPON_STINGER = { item = 'stinger', label = ('weapon_stinger') },
    WEAPON_MINIGUN = { item = 'minigun', label = ('weapon_minigun') },
    WEAPON_GRENADE = { item = 'grenade', label = ('weapon_grenade') },
    WEAPON_STICKYBOMB = { item = 'stickybomb', label = ('weapon_stickybomb') },
    WEAPON_SMOKEGRENADE = { item = 'smokegrenade', label = ('weapon_smokegrenade') },
    WEAPON_BZGAS = { item = 'bzgas', label = ('weapon_bzgas') },
    WEAPON_MOLOTOV = { item = 'molotov', label = ('weapon_molotov') },
    WEAPON_FIREEXTINGUISHER = { item = 'fireextinguisher', label = ('weapon_fireextinguisher') },
    WEAPON_PETROLCAN = { item = 'petrolcan', label = ('weapon_petrolcan') },
    WEAPON_DIGISCANNER = { item = 'digiscanner', label = ('weapon_digiscanner') },
    WEAPON_BALL = { item = 'ball', label = ('weapon_ball') },
    WEAPON_SNSPISTOL = { item = 'snspistol', label = ('weapon_snspistol') },
    WEAPON_BOTTLE = { item = 'bottle', label = ('weapon_bottle') },
    WEAPON_GUSENBERG = { item = 'gusenberg', label = ('weapon_gusenberg') },
    WEAPON_SPECIALCARBINE = { item = 'specialcarbine', label = ('weapon_specialcarbine') },
    WEAPON_HEAVYPISTOL = { item = 'heavypistol', label = ('weapon_heavypistol') },
    WEAPON_BULLPUPRIFLE = { item = 'bullpuprifle', label = ('weapon_bullpuprifle') },
    WEAPON_DAGGER = { item = 'dagger', label = ('weapon_dagger') },
    WEAPON_VINTAGEPISTOL = { item = 'vintagepistol', label = ('weapon_vintagepistol') },
    WEAPON_FIREWORK = { item = 'firework', label = ('weapon_firework') },
    WEAPON_MUSKET = { item = 'musket', label = ('weapon_musket') },
    WEAPON_HEAVYSHOTGUN = { item = 'heavyshotgun', label = ('weapon_heavyshotgun') },
    WEAPON_MARKSMANRIFLE = { item = 'marksmanrifle', label = ('weapon_marksmanrifle') },
    WEAPON_HOMINGLAUNCHER = { item = 'hominglauncher', label = ('weapon_hominglauncher') },
    WEAPON_PROXMINE = { item = 'proxmine', label = ('weapon_proxmine') },
    WEAPON_SNOWBALL = { item = 'snowball', label = ('weapon_snowball') },
    WEAPON_FLAREGUN = { item = 'flaregun', label = ('weapon_flaregun') },
    WEAPON_GARBAGEBAG = { item = 'garbagebag', label = ('weapon_garbagebag') },
    WEAPON_HANDCUFFS = { item = 'handcuffs', label = ('weapon_handcuffs') },
    WEAPON_COMBATPDW = { item = 'combatpdw', label = ('weapon_combatpdw') },
    WEAPON_MARKSMANPISTOL = { item = 'marksmanpistol', label = ('weapon_marksmanpistol') },
    WEAPON_KNUCKLE = { item = 'knuckle', label = ('weapon_knuckle') },
    WEAPON_HATCHET = { item = 'hatchet', label = ('weapon_hatchet') },
    WEAPON_RAILGUN = { item = 'railgun', label = ('weapon_railgun') },
    WEAPON_MACHETE = { item = 'machete', label = ('weapon_machete') },
    WEAPON_MACHINEPISTOL = { item = 'machinepistol', label = ('weapon_machinepistol') },
    WEAPON_SWITCHBLADE = { item = 'switchblade', label = ('weapon_switchblade') },
    WEAPON_REVOLVER = { item = 'revolver', label = ('weapon_revolver') },
    WEAPON_DBSHOTGUN = { item = 'dbshotgun', label = ('weapon_dbshotgun') },
    WEAPON_COMPACTRIFLE = { item = 'compactrifle', label = ('weapon_compactrifle') },
    WEAPON_AUTOSHOTGUN = { item = 'autoshotgun', label = ('weapon_autoshotgun') },
    WEAPON_BATTLEAXE = { item = 'battleaxe', label = ('weapon_battleaxe') },
    WEAPON_COMPACTLAUNCHER = { item = 'compactlauncher', label = ('weapon_compactlauncher') },
    WEAPON_MINISMG = { item = 'minismg', label = ('weapon_minismg') },
    WEAPON_PIPEBOMB = { item = 'pipebomb', label = ('weapon_pipebomb') },
    WEAPON_POOLCUE = { item = 'poolcue', label = ('weapon_poolcue') },
    WEAPON_WRENCH = { item = 'wrench', label = ('weapon_wrench') },
    WEAPON_FLASHLIGHT = { item = 'flashlight', label = ('weapon_flashlight') },
    GADGET_NIGHTVISION = { item = 'nightvision', label = ('gadget_nightvision') },
    GADGET_PARACHUTE = { item = 'parachute', label = ('gadget_parachute') },
    WEAPON_FLARE = { item = 'flare', label = ('weapon_flare') }, 
    WEAPON_SNSPISTOL_MK2 = { item = 'snspistol_mk2', label = ('weapon_snspistol_mk2') }, 
    WEAPON_REVOLVER_MK2 = { item = 'revolver_mk2', label = ('weapon_revolver_mk2') },  
    WEAPON_DOUBLEACTION = { item = 'doubleaction', label = ('weapon_doubleaction') },    
    WEAPON_SPECIALCARBINE_MK2 = { item = 'specialcarbine_mk2', label = ('weapon_specialcarabine_mk2') },  
    WEAPON_BULLPUPRIFLE_MK2 = { item = 'bullpuprifle_mk2', label = ('weapon_bullpruprifle_mk2') },   
    WEAPON_PUMPSHOTGUN_MK2 = { item = 'pumpshotgun_mk2', label = ('weapon_pumpshotgun_mk2') },
    WEAPON_MARKSMANRIFLE_MK2 = { item = 'marksmanrifle_mk2', label = ('weapon_marksmanrifle_mk2') },  
    WEAPON_ASSAULTRIFLE_MK2 = { item = 'assaultrifle_mk2', label = ('weapon_assaultrifle_mk2') },
    WEAPON_CARBINERIFLE_MK2 = { item = 'carbinerifle_mk2', label = ('weapon_carbinerifle_mk2') },  
    WEAPON_COMBATMG_MK2 = { item = 'combatmg_mk2', label = ('weapon_combatmg_mk2') },   
    WEAPON_HEAVYSNIPER_MK2 = { item = 'heavysniper_mk2', label = ('weapon_heavysniper_mk2') },   
    WEAPON_PISTOL_MK2 = { item = 'pistol_mk2', label = ('weapon_pistol_mk2') },   
    WEAPON_SMG_MK2 = { item = 'smg_mk2', label = ('weapon_smg_mk2') }
}

Config.AmmoTypes = {
    AMMO_PISTOL = { item = 'pistol_ammo' },
    AMMO_SMG = { item = 'smg_ammo' },
    AMMO_FIREWORK = { item = 'firework_ammo' },
    AMMO_RIFLE = { item = 'rifle_ammo' },
    AMMO_MG = { item = 'mg_ammo' },
    AMMO_SHOTGUN = { item = 'shotgun_ammo' },
    AMMO_STUNGUN = { item = 'stungun_ammo' },
    AMMO_SNIPER = { item = 'sniper_ammo' },
    AMMO_SNIPER_REMOTE = { item = 'sniper_remote_ammo' },
    AMMO_MINIGUN = { item = 'minigun_ammo' },
    AMMO_GRENADELAUNCHER = { item = 'grenadelauncher_ammo' },
    AMMO_GRENADELAUNCHER_SMOKE = { item = 'grenadelauncher_smoke_ammo' },
    AMMO_RPG = { item = 'rpg_ammo' },
    AMMO_STINGER = { item = 'stinger_ammo' },
    AMMO_BALL = { item = 'ball' },
    AMMO_STICKYBOMB = { item = 'stickybomb' },
    AMMO_SMOKEGRENADE = { item = 'smokegrenade' },
    AMMO_BZGAS = { item = 'gzgas_ammo' },
    AMMO_FLARE = { item = 'flare_ammo' },
    AMMO_MOLOTOV = { item = 'molotov' },
    AMMO_TANK = { item = 'tank_ammo' },
    AMMO_SPACE_ROCKET = { item = 'space_rocket_ammo' },
    AMMO_PLANE_ROCKET = { item = 'plane_rocket_ammo' },
    AMMO_PLAYER_LASER = { item = 'player_laser_ammo' },
    AMMO_ENEMY_LASER = { item = 'enemy_laser_ammo' },
    AMMO_BIRD_CRAP = { item = 'bird_crap_ammo' }
}